name: Availability of external services

on:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ dev_alban, dev_thomas, master ]
  pull_request:
    branches: [ dev_alban, dev_thomas, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Bio.tools SPARQL endpoint
        run: bash biotools-sparql.alive.sh