name: Black code formatting

on:
  #workflow_run:
  #  workflows: ["Python application"]
  #  types: [completed]
  push:
    branches: [ dev_alban, dev_thomas, master ]
  pull_request:
    branches: [ dev_alban, dev_thomas, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --diff --color"