name: Black code formatting

on:
  #workflow_run:
  #  workflows: ["Python application"]
  #  types: [completed]
  push:
    branches: [dev_alban, dev_thomas, master, pre_deploy_1.1]
  pull_request:
    branches: [dev_alban, dev_thomas, master, pre_deploy_1.1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: ". --check --diff --color"
          version: "22.12.0"
