name: Code formatting

on:
  #workflow_run:
  #  workflows: ["Python application"]
  #  types: [completed]
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: ". --check --diff --color"
          version: "26.5.1"
